[2018-04-01 22:40:25 +0600] [27101] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x1069d55f0>
  errorlog: /Users/seal/Desktop/oneoffnotes/gunicorn-error.log
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 2
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x1069d5320>
  pre_fork: <function pre_fork at 0x1069d5488>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: /Users/seal/Desktop/oneoffnotes/gunicorn-access.log
  group: 20
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x1069d51b8>
  pre_exec: <function pre_exec at 0x1069d5b90>
  worker_tmp_dir: None
  limit_request_fields: 100
  pythonpath: None
  on_exit: <function on_exit at 0x1069d9410>
  config: gunicorn.conf.py
  logconfig: None
  check_config: False
  statsd_prefix: 
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  reload_engine: auto
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x1069d5cf8>
  post_request: <function post_request at 0x1069d5de8>
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x1069d58c0>
  raw_paste_global_conf: []
  threads: 1
  max_requests: 0
  chdir: /Users/seal/Desktop/oneoffnotes
  daemon: False
  user: 501
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  on_starting: <function on_starting at 0x1069d5050>
  post_worker_init: <function post_worker_init at 0x1069d5758>
  child_exit: <function child_exit at 0x1069d5f50>
  worker_exit: <function worker_exit at 0x1069d9140>
  paste: None
  default_proc_name: testproject.wsgi
  syslog_addr: unix:///var/run/syslog
  syslog_prefix: None
  ciphers: TLSv1
  worker_abort: <function worker_abort at 0x1069d5a28>
  loglevel: debug
  bind: ['*:80']
  raw_env: []
  initgroups: False
  capture_output: False
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x1069d92a8>
  timeout: 30
  keyfile: None
  ca_certs: None
  tmp_upload_dir: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2018-04-01 22:40:25 +0600] [27101] [INFO] Starting gunicorn 19.7.1
[2018-04-01 22:40:26 +0600] [27101] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:40:26 +0600] [27101] [ERROR] Retrying in 1 second.
[2018-04-01 22:40:27 +0600] [27101] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:40:27 +0600] [27101] [ERROR] Retrying in 1 second.
[2018-04-01 22:40:28 +0600] [27101] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:40:28 +0600] [27101] [ERROR] Retrying in 1 second.
[2018-04-01 22:40:29 +0600] [27101] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:40:29 +0600] [27101] [ERROR] Retrying in 1 second.
[2018-04-01 22:40:30 +0600] [27101] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:40:30 +0600] [27101] [ERROR] Retrying in 1 second.
[2018-04-01 22:40:31 +0600] [27101] [ERROR] Can't connect to ('*', 80)
[2018-04-01 22:40:45 +0600] [27121] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x1032c75f0>
  errorlog: /Users/seal/Desktop/oneoffnotes/gunicorn-error.log
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 2
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x1032c7320>
  pre_fork: <function pre_fork at 0x1032c7488>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: /Users/seal/Desktop/oneoffnotes/gunicorn-access.log
  group: 20
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x1032c71b8>
  pre_exec: <function pre_exec at 0x1032c7b90>
  worker_tmp_dir: None
  limit_request_fields: 100
  pythonpath: None
  on_exit: <function on_exit at 0x1032cb410>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  reload_engine: auto
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x1032c7cf8>
  post_request: <function post_request at 0x1032c7de8>
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x1032c78c0>
  raw_paste_global_conf: []
  threads: 1
  max_requests: 0
  chdir: /Users/seal/Desktop/oneoffnotes
  daemon: False
  user: 501
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  on_starting: <function on_starting at 0x1032c7050>
  post_worker_init: <function post_worker_init at 0x1032c7758>
  child_exit: <function child_exit at 0x1032c7f50>
  worker_exit: <function worker_exit at 0x1032cb140>
  paste: None
  default_proc_name: testproject.wsgi
  syslog_addr: unix:///var/run/syslog
  syslog_prefix: None
  ciphers: TLSv1
  worker_abort: <function worker_abort at 0x1032c7a28>
  loglevel: debug
  bind: ['*:80']
  raw_env: []
  initgroups: False
  capture_output: False
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x1032cb2a8>
  timeout: 30
  keyfile: None
  ca_certs: None
  tmp_upload_dir: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2018-04-01 22:40:45 +0600] [27121] [INFO] Starting gunicorn 19.7.1
[2018-04-01 22:40:45 +0600] [27121] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:40:45 +0600] [27121] [ERROR] Retrying in 1 second.
[2018-04-01 22:40:46 +0600] [27121] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:40:46 +0600] [27121] [ERROR] Retrying in 1 second.
[2018-04-01 22:40:47 +0600] [27121] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:40:47 +0600] [27121] [ERROR] Retrying in 1 second.
[2018-04-01 22:40:48 +0600] [27121] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:40:48 +0600] [27121] [ERROR] Retrying in 1 second.
[2018-04-01 22:40:49 +0600] [27121] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:40:49 +0600] [27121] [ERROR] Retrying in 1 second.
[2018-04-01 22:40:50 +0600] [27121] [ERROR] Can't connect to ('*', 80)
[2018-04-01 22:41:11 +0600] [27153] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x1041c55f0>
  errorlog: /Users/seal/Desktop/oneoffnotes/gunicorn-error.log
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 2
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x1041c5320>
  pre_fork: <function pre_fork at 0x1041c5488>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: /Users/seal/Desktop/oneoffnotes/gunicorn-access.log
  group: 20
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x1041c51b8>
  pre_exec: <function pre_exec at 0x1041c5b90>
  worker_tmp_dir: None
  limit_request_fields: 100
  pythonpath: None
  on_exit: <function on_exit at 0x1041c9410>
  config: None
  logconfig: None
  check_config: False
  statsd_prefix: 
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  reload_engine: auto
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x1041c5cf8>
  post_request: <function post_request at 0x1041c5de8>
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x1041c58c0>
  raw_paste_global_conf: []
  threads: 1
  max_requests: 0
  chdir: /Users/seal/Desktop/oneoffnotes
  daemon: False
  user: 501
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  on_starting: <function on_starting at 0x1041c5050>
  post_worker_init: <function post_worker_init at 0x1041c5758>
  child_exit: <function child_exit at 0x1041c5f50>
  worker_exit: <function worker_exit at 0x1041c9140>
  paste: None
  default_proc_name: oneoffnotes.wsgi
  syslog_addr: unix:///var/run/syslog
  syslog_prefix: None
  ciphers: TLSv1
  worker_abort: <function worker_abort at 0x1041c5a28>
  loglevel: debug
  bind: ['*:80']
  raw_env: []
  initgroups: False
  capture_output: False
  reload: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x1041c92a8>
  timeout: 30
  keyfile: None
  ca_certs: None
  tmp_upload_dir: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
[2018-04-01 22:41:11 +0600] [27153] [INFO] Starting gunicorn 19.7.1
[2018-04-01 22:41:11 +0600] [27153] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:41:11 +0600] [27153] [ERROR] Retrying in 1 second.
[2018-04-01 22:41:12 +0600] [27153] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:41:12 +0600] [27153] [ERROR] Retrying in 1 second.
[2018-04-01 22:41:13 +0600] [27153] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:41:13 +0600] [27153] [ERROR] Retrying in 1 second.
[2018-04-01 22:41:14 +0600] [27153] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:41:14 +0600] [27153] [ERROR] Retrying in 1 second.
[2018-04-01 22:41:15 +0600] [27153] [DEBUG] connection to ('*', 80) failed: [Errno 8] nodename nor servname provided, or not known
[2018-04-01 22:41:15 +0600] [27153] [ERROR] Retrying in 1 second.
[2018-04-01 22:41:16 +0600] [27153] [ERROR] Can't connect to ('*', 80)
